image: atlassian/default-image:2

pipelines:
    branches:
      backend:
        - step:
           script:
             - git checkout backend
             - git pull    
             - git remote add sync git@github.com:ishavora31/devops.git
             - git push sync backend